[2024-09-16T12:55:41.857+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-16T12:55:43.224+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airbyte_sync_tables_postgres.airbyte_check_sync manual__2024-09-16T12:53:42.505250+00:00 [queued]>
[2024-09-16T12:55:43.577+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airbyte_sync_tables_postgres.airbyte_check_sync manual__2024-09-16T12:53:42.505250+00:00 [queued]>
[2024-09-16T12:55:43.594+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-16T12:55:44.582+0000] {taskinstance.py:2330} INFO - Executing <Task(AirbyteJobSensor): airbyte_check_sync> on 2024-09-16 12:53:42.505250+00:00
[2024-09-16T12:55:47.378+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'airbyte_sync_tables_postgres', 'airbyte_check_sync', 'manual__2024-09-16T12:53:42.505250+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/airbyte_sync_tables_postgres.py', '--cfg-path', '/tmp/tmp_g4sfiwm']
[2024-09-16T12:55:47.468+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask airbyte_check_sync
[2024-09-16T12:55:47.980+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=57704) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-16T12:55:47.992+0000] {standard_task_runner.py:64} INFO - Started process 57714 to run task
[2024-09-16T12:55:53.784+0000] {task_command.py:426} INFO - Running <TaskInstance: airbyte_sync_tables_postgres.airbyte_check_sync manual__2024-09-16T12:53:42.505250+00:00 [running]> on host e532e2e16082
[2024-09-16T12:55:59.957+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vizentec-engdados' AIRFLOW_CTX_DAG_ID='airbyte_sync_tables_postgres' AIRFLOW_CTX_TASK_ID='airbyte_check_sync' AIRFLOW_CTX_EXECUTION_DATE='2024-09-16T12:53:42.505250+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-16T12:53:42.505250+00:00'
[2024-09-16T12:55:59.972+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-16T12:56:01.785+0000] {baseoperator.py:400} WARNING - AirbyteJobSensor.execute cannot be called outside TaskInstance!
[2024-09-16T12:56:03.275+0000] {base.py:84} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-09-16T12:56:04.009+0000] {airbyte.py:113} INFO - Waiting for job 17 to complete.
[2024-09-16T12:57:04.191+0000] {base.py:84} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-09-16T12:57:07.115+0000] {airbyte.py:108} INFO - Job 17 completed successfully.
[2024-09-16T12:57:07.131+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-09-16T12:57:07.142+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-16T12:57:07.341+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=airbyte_sync_tables_postgres, task_id=airbyte_check_sync, run_id=manual__2024-09-16T12:53:42.505250+00:00, execution_date=20240916T125342, start_date=20240916T125543, end_date=20240916T125707
[2024-09-16T12:57:07.720+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-16T12:57:08.716+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-16T12:57:08.794+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
