[2024-10-23T11:43:47.207+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-23T11:43:47.373+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airbyte_sync_tables_postgres.sync_schemas.SSO.airbyte_trigger_sync_SSO scheduled__2024-10-22T00:00:00+00:00 [queued]>
[2024-10-23T11:43:47.390+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airbyte_sync_tables_postgres.sync_schemas.SSO.airbyte_trigger_sync_SSO scheduled__2024-10-22T00:00:00+00:00 [queued]>
[2024-10-23T11:43:47.391+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-10-23T11:43:47.490+0000] {taskinstance.py:2330} INFO - Executing <Task(AirbyteTriggerSyncOperator): sync_schemas.SSO.airbyte_trigger_sync_SSO> on 2024-10-22 00:00:00+00:00
[2024-10-23T11:43:47.503+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'airbyte_sync_tables_postgres', 'sync_schemas.SSO.airbyte_trigger_sync_SSO', 'scheduled__2024-10-22T00:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/airbyte_sync_tables_postgres.py', '--cfg-path', '/tmp/tmp0y6trcmw']
[2024-10-23T11:43:47.575+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=3434) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-23T11:43:47.576+0000] {standard_task_runner.py:91} INFO - Job 58: Subtask sync_schemas.SSO.airbyte_trigger_sync_SSO
[2024-10-23T11:43:47.577+0000] {standard_task_runner.py:64} INFO - Started process 3437 to run task
[2024-10-23T11:43:47.795+0000] {task_command.py:426} INFO - Running <TaskInstance: airbyte_sync_tables_postgres.sync_schemas.SSO.airbyte_trigger_sync_SSO scheduled__2024-10-22T00:00:00+00:00 [running]> on host efbb3a47dac9
[2024-10-23T11:43:48.189+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vizentec-engdados' AIRFLOW_CTX_DAG_ID='airbyte_sync_tables_postgres' AIRFLOW_CTX_TASK_ID='sync_schemas.SSO.airbyte_trigger_sync_SSO' AIRFLOW_CTX_EXECUTION_DATE='2024-10-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-22T00:00:00+00:00'
[2024-10-23T11:43:48.190+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-23T11:43:48.291+0000] {base.py:84} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-10-23T11:43:49.470+0000] {airbyte.py:95} INFO - Job 29 was submitted to Airbyte Server
[2024-10-23T11:43:49.472+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-23T11:43:49.504+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=airbyte_sync_tables_postgres, task_id=sync_schemas.SSO.airbyte_trigger_sync_SSO, run_id=scheduled__2024-10-22T00:00:00+00:00, execution_date=20241022T000000, start_date=20241023T114347, end_date=20241023T114349
[2024-10-23T11:43:49.531+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-10-23T11:43:49.604+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-23T11:43:49.607+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
