[2024-10-12T13:18:45.501+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-12T13:18:45.537+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airbyte_sync_tables_postgres.sync_schemas.SSO.airbyte_check_sync_SSO manual__2024-10-12T13:18:35.945033+00:00 [queued]>
[2024-10-12T13:18:45.628+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airbyte_sync_tables_postgres.sync_schemas.SSO.airbyte_check_sync_SSO manual__2024-10-12T13:18:35.945033+00:00 [queued]>
[2024-10-12T13:18:45.630+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-12T13:18:45.824+0000] {taskinstance.py:2330} INFO - Executing <Task(AirbyteJobSensor): sync_schemas.SSO.airbyte_check_sync_SSO> on 2024-10-12 13:18:35.945033+00:00
[2024-10-12T13:18:45.908+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'airbyte_sync_tables_postgres', 'sync_schemas.SSO.airbyte_check_sync_SSO', 'manual__2024-10-12T13:18:35.945033+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/airbyte_sync_tables_postgres.py', '--cfg-path', '/tmp/tmpc69ubt98']
[2024-10-12T13:18:45.916+0000] {standard_task_runner.py:91} INFO - Job 29: Subtask sync_schemas.SSO.airbyte_check_sync_SSO
[2024-10-12T13:18:45.998+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=25645) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-12T13:18:46.001+0000] {standard_task_runner.py:64} INFO - Started process 25648 to run task
[2024-10-12T13:18:46.310+0000] {task_command.py:426} INFO - Running <TaskInstance: airbyte_sync_tables_postgres.sync_schemas.SSO.airbyte_check_sync_SSO manual__2024-10-12T13:18:35.945033+00:00 [running]> on host efbb3a47dac9
[2024-10-12T13:18:46.830+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vizentec-engdados' AIRFLOW_CTX_DAG_ID='airbyte_sync_tables_postgres' AIRFLOW_CTX_TASK_ID='sync_schemas.SSO.airbyte_check_sync_SSO' AIRFLOW_CTX_EXECUTION_DATE='2024-10-12T13:18:35.945033+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-12T13:18:35.945033+00:00'
[2024-10-12T13:18:46.832+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-12T13:18:46.919+0000] {baseoperator.py:400} WARNING - AirbyteJobSensor.execute cannot be called outside TaskInstance!
[2024-10-12T13:18:46.931+0000] {base.py:84} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-10-12T13:18:47.072+0000] {airbyte.py:113} INFO - Waiting for job 27 to complete.
[2024-10-12T13:19:47.083+0000] {base.py:84} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-10-12T13:19:47.451+0000] {airbyte.py:113} INFO - Waiting for job 27 to complete.
[2024-10-12T13:20:47.492+0000] {base.py:84} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-10-12T13:20:47.797+0000] {airbyte.py:108} INFO - Job 27 completed successfully.
[2024-10-12T13:20:47.798+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-10-12T13:20:47.799+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-12T13:20:47.811+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=airbyte_sync_tables_postgres, task_id=sync_schemas.SSO.airbyte_check_sync_SSO, run_id=manual__2024-10-12T13:18:35.945033+00:00, execution_date=20241012T131835, start_date=20241012T131845, end_date=20241012T132047
[2024-10-12T13:20:47.849+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-10-12T13:20:47.885+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-12T13:20:47.887+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
