[2024-09-14T20:54:31.194+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-14T20:54:31.349+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airbyte_sync_tables_postgres.airbyte_check_sync manual__2024-09-14T20:54:24.497914+00:00 [queued]>
[2024-09-14T20:54:31.401+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airbyte_sync_tables_postgres.airbyte_check_sync manual__2024-09-14T20:54:24.497914+00:00 [queued]>
[2024-09-14T20:54:31.407+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-09-14T20:54:31.532+0000] {taskinstance.py:2330} INFO - Executing <Task(AirbyteJobSensor): airbyte_check_sync> on 2024-09-14 20:54:24.497914+00:00
[2024-09-14T20:54:31.590+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'airbyte_sync_tables_postgres', 'airbyte_check_sync', 'manual__2024-09-14T20:54:24.497914+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/airbyte_sync_tables_postgres.py', '--cfg-path', '/tmp/tmpt0nszg3l']
[2024-09-14T20:54:31.659+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask airbyte_check_sync
[2024-09-14T20:54:31.670+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=374) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-14T20:54:31.678+0000] {standard_task_runner.py:64} INFO - Started process 375 to run task
[2024-09-14T20:54:32.081+0000] {task_command.py:426} INFO - Running <TaskInstance: airbyte_sync_tables_postgres.airbyte_check_sync manual__2024-09-14T20:54:24.497914+00:00 [running]> on host e532e2e16082
[2024-09-14T20:54:33.572+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vizentec-engdados' AIRFLOW_CTX_DAG_ID='airbyte_sync_tables_postgres' AIRFLOW_CTX_TASK_ID='airbyte_check_sync' AIRFLOW_CTX_EXECUTION_DATE='2024-09-14T20:54:24.497914+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-14T20:54:24.497914+00:00'
[2024-09-14T20:54:33.610+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-14T20:54:33.948+0000] {baseoperator.py:400} WARNING - AirbyteJobSensor.execute cannot be called outside TaskInstance!
[2024-09-14T20:54:34.045+0000] {base.py:84} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-09-14T20:54:34.240+0000] {airbyte.py:113} INFO - Waiting for job 16 to complete.
[2024-09-14T20:55:34.254+0000] {base.py:84} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-09-14T20:55:34.430+0000] {airbyte.py:113} INFO - Waiting for job 16 to complete.
[2024-09-14T20:56:34.444+0000] {base.py:84} INFO - Using connection ID 'airbyte_conn' for task execution.
[2024-09-14T20:56:34.700+0000] {airbyte.py:108} INFO - Job 16 completed successfully.
[2024-09-14T20:56:34.703+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-09-14T20:56:34.706+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-14T20:56:34.728+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=airbyte_sync_tables_postgres, task_id=airbyte_check_sync, run_id=manual__2024-09-14T20:54:24.497914+00:00, execution_date=20240914T205424, start_date=20240914T205431, end_date=20240914T205634
[2024-09-14T20:56:34.794+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-09-14T20:56:34.823+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-14T20:56:34.825+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
